import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Client-Info,Apikey"};
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
async function admin(token:string,id:string){const {data:s}=await db.from("admin_auth_sessions").select("admin_id,expires_at").eq("token",token).maybeSingle();if(!s||s.admin_id!==id||new Date(s.expires_at)<=new Date())return false;const {data:a}=await db.from("admin_users").select("id,role,is_active").eq("id",id).maybeSingle();return !!a&&a.role==="super_admin"&&a.is_active===true;}
function out(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});try{const b=await req.json();if(!await admin(String(b.admin_session_token||""),String(b.admin_id||"")))return out({error:"Unauthorized"},401);
switch(b.action){
case "bookings":{const {data,error}=await db.from("bookings").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load bookings"},500);return out({bookings:data||[]});}
case "technicians":{const {data,error}=await db.from("technicians").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load technicians"},500);return out({technicians:data||[]});}
case "customers":{const {data,error}=await db.from("customers").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load customers"},500);return out({customers:data||[]});}
case "booking_status":{const {data,error}=await db.from("bookings").update({status:b.status,updated_at:new Date().toISOString()}).eq("id",b.booking_id).select("*").single();if(error)return out({error:"Unable to update booking"},400);return out({booking:data});}
case "assign":{if(!b.booking_id||!b.technician_id)return out({error:"Booking and technician are required"},400);const {data:job,error:je}=await db.from("technician_jobs").insert({booking_id:b.booking_id,technician_id:b.technician_id,status:"assigned"}).select().single();if(je)return out({error:"Unable to create technician job"},400);const {data:booking,error:be}=await db.from("bookings").update({assigned_technician_id:b.technician_id,status:"confirmed",updated_at:new Date().toISOString()}).eq("id",b.booking_id).select("*").single();if(be)return out({error:"Unable to assign booking"},400);return out({booking,job});}
case "technician_status":{const update:any={status:b.status};if(["rejected","inactive"].includes(b.status))update.rejection_reason=b.reason||null;if(b.status==="suspended")update.suspend_reason=b.reason||null;if(b.status==="active"){update.rejection_reason=null;update.suspend_reason=null;}const {data,error}=await db.from("technicians").update(update).eq("id",b.technician_id).select("*").single();if(error)return out({error:"Unable to update technician"},400);return out({technician:data});}
case "recharge_status":{const update:any={status:b.status,approved_at:new Date().toISOString(),approved_by:String(b.admin_id)};if(b.status==="rejected")update.admin_notes=b.reason||null;const {data,error}=await db.from("wallet_recharges").update(update).eq("id",b.recharge_id).select("*").single();if(error)return out({error:"Unable to update recharge"},400);return out({recharge:data});}
case "wallet_transactions":{const {data,error}=await db.from("wallet_transactions").select("*").order("created_at",{ascending:false}).limit(100);if(error)return out({error:"Unable to load wallet transactions"},500);return out({transactions:data||[]});}
case "recharges":{const {data,error}=await db.from("wallet_recharges").select("*, technician:technicians(full_name)").order("created_at",{ascending:false}).limit(50);if(error)return out({error:"Unable to load recharge requests"},500);return out({recharges:data||[]});}
case "payments":{const {data,error}=await db.from("payments").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load payments"},500);return out({payments:data||[]});}
case "notifications":{const {data,error}=await db.from("notifications").select("*").eq("recipient_type","admin").eq("recipient_id","admin").order("created_at",{ascending:false}).limit(Number(b.limit)||100);if(error)return out({error:"Unable to load notifications"},500);return out({notifications:data||[]});}
case "service_prices":{const {data,error}=await db.from("service_prices").select("*").order("service_name");if(error)return out({error:"Unable to load service prices"},500);return out({prices:data||[]});}
case "save_service_prices":{const updates=Array.isArray(b.updates)?b.updates:[];for(const u of updates){const {error}=await db.from("service_prices").update({base_price:Number(u.base_price)||0,gst_rate:Number(u.gst_rate)||0,platform_fee:Number(u.platform_fee)||0,commission_rate:Number(u.commission_rate)||0,is_active:Boolean(u.is_active),updated_at:new Date().toISOString()}).eq("id",String(u.id));if(error)return out({error:"Unable to save service prices"},400);}return out({success:true});}
case "site_settings":{const {data,error}=await db.from("site_settings").select("*").eq("id",1).maybeSingle();if(error)return out({error:"Unable to load site settings"},500);return out({settings:data||null});}
case "save_site_settings":{const input=b.input||{};const payload={id:1,google_business_url:input.google_business_url||null,facebook_url:input.facebook_url||null,instagram_url:input.instagram_url||null,twitter_url:input.twitter_url||null,youtube_url:input.youtube_url||null,whatsapp_number:input.whatsapp_number||null,website_url:input.website_url||null,updated_at:new Date().toISOString(),updated_by:String(b.admin_id)};const {error}=await db.from("site_settings").upsert(payload,{onConflict:"id"});if(error)return out({error:"Unable to save site settings"},400);return out({success:true});}
default:return out({error:"Invalid action"},400)}}catch{return out({error:"Unexpected server error"},500)}});