import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Client-Info,Apikey"};
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
async function admin(token:string,id:string){const {data:s}=await db.from("admin_auth_sessions").select("admin_id,expires_at").eq("token",token).maybeSingle();if(!s||s.admin_id!==id||new Date(s.expires_at)<=new Date())return false;const {data:a}=await db.from("admin_users").select("id,role,is_active").eq("id",id).maybeSingle();return !!a&&a.role==="super_admin"&&a.is_active===true;}
function out(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});try{const b=await req.json();if(!await admin(String(b.admin_session_token||""),String(b.admin_id||"")))return out({error:"Unauthorized"},401);
switch(b.action){
case "analytics_summary":{const [{data:bookings},{data:technicians},{data:customers},{data:reviews}]=await Promise.all([db.from("bookings").select("status,created_at,total_amount,amount,job_completed_at,customer_id,mobile_number"),db.from("technicians").select("status,wallet_locked"),db.from("customers").select("id"),db.from("reviews").select("rating")]);const today=new Date().toISOString().split("T")[0];const bs=bookings||[];const ts=technicians||[];const cs=customers||[];const rs=reviews||[];const todayBs=bs.filter((b:any)=>b.created_at?.startsWith(today));const active=new Set(bs.filter((b:any)=>b.created_at>new Date(Date.now()-30*86400000).toISOString()).map((b:any)=>b.customer_id||b.mobile_number));const avg=rs.length?rs.reduce((n:any,r:any)=>n+Number(r.rating||0),0)/rs.length:0;return out({summary:{todayRevenue:todayBs.filter((b:any)=>b.status==="completed").reduce((n:any,b:any)=>n+Number(b.total_amount??b.amount??0),0),pendingBookings:bs.filter((b:any)=>["pending","assigned","in_progress","job_started"].includes(b.status)).length,cancelledJobs:bs.filter((b:any)=>b.status==="cancelled").length,availableTechnicians:ts.filter((t:any)=>t.status==="active"&&!t.wallet_locked).length,inactiveCustomers:Math.max(0,cs.length-active.size),totalCustomers:cs.length,totalTechnicians:ts.length,newBookingsToday:todayBs.length,completedJobsToday:bs.filter((b:any)=>b.status==="completed"&&b.job_completed_at?.startsWith(today)).length,avgRating:Math.round(avg*10)/10}});}
case "analytics_revenue":{const days=Math.min(90,Math.max(1,Number(b.days)||30));const {data:bookings,error}=await db.from("bookings").select("total_amount,amount,status,created_at").order("created_at",{ascending:true}).limit(2000);if(error)return out({error:"Unable to load analytics"},500);const cutoff=Date.now()-days*86400000;const map=new Map<string,{revenue:number;bookings:number}>();for(const x of (bookings||[]) as any[]){if(new Date(x.created_at).getTime()<cutoff)continue;const date=x.created_at.split("T")[0];const v=map.get(date)||{revenue:0,bookings:0};v.bookings++;if(x.status==="completed")v.revenue+=Number(x.total_amount??x.amount??0);map.set(date,v)}return out({revenueData:Array.from(map.entries()).map(([date,v])=>({date,...v}))});}
case "bookings":{const {data,error}=await db.from("bookings").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load bookings"},500);return out({bookings:data||[]});}
case "technicians":{const {data,error}=await db.from("technicians").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load technicians"},500);return out({technicians:data||[]});}
case "customers":{const {data,error}=await db.from("customers").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load customers"},500);return out({customers:data||[]});}
case "booking_status":{const allowed=["pending","confirmed","assigned","accepted","on_the_way","in_progress","job_started","job_completed","completed","cancelled"];if(!allowed.includes(String(b.status)))return out({error:"Invalid booking status"},400);const {data,error}=await db.from("bookings").update({status:b.status,updated_at:new Date().toISOString()}).eq("id",b.booking_id).select("*").single();if(error)return out({error:"Unable to update booking"},400);return out({booking:data});}
case "assign":{if(!b.booking_id||!b.technician_id)return out({error:"Booking and technician are required"},400);const {data:job,error:je}=await db.from("technician_jobs").insert({booking_id:b.booking_id,technician_id:b.technician_id,status:"assigned"}).select().single();if(je)return out({error:"Unable to create technician job"},400);const {data:booking,error:be}=await db.from("bookings").update({assigned_technician_id:b.technician_id,status:"confirmed",updated_at:new Date().toISOString()}).eq("id",b.booking_id).select("*").single();if(be){await db.from("technician_jobs").delete().eq("id",job.id);return out({error:"Unable to assign booking"},400);}return out({booking,job});}
case "technician_status":{if(!["active","inactive","rejected","suspended"].includes(String(b.status)))return out({error:"Invalid technician status"},400);const update:any={status:b.status};if(["rejected","inactive"].includes(b.status))update.rejection_reason=b.reason||null;if(b.status==="suspended")update.suspend_reason=b.reason||null;if(b.status==="active"){update.rejection_reason=null;update.suspend_reason=null;}const {data,error}=await db.from("technicians").update(update).eq("id",b.technician_id).select("*").single();if(error)return out({error:"Unable to update technician"},400);return out({technician:data});}
case "recharge_status":{if(!["approved","rejected"].includes(String(b.status)))return out({error:"Invalid recharge status"},400);const update:any={status:b.status,approved_at:new Date().toISOString(),approved_by:String(b.admin_id)};if(b.status==="rejected")update.admin_notes=b.reason||null;const {data,error}=await db.from("wallet_recharges").update(update).eq("id",b.recharge_id).select("*").single();if(error)return out({error:"Unable to update recharge"},400);return out({recharge:data});}
case "wallet_transactions":{const {data,error}=await db.from("wallet_transactions").select("*").order("created_at",{ascending:false}).limit(100);if(error)return out({error:"Unable to load wallet transactions"},500);return out({transactions:data||[]});}
case "recharges":{const {data,error}=await db.from("wallet_recharges").select("*, technician:technicians(full_name)").order("created_at",{ascending:false}).limit(50);if(error)return out({error:"Unable to load recharge requests"},500);return out({recharges:data||[]});}
case "payments":{const {data,error}=await db.from("payments").select("*").order("created_at",{ascending:false});if(error)return out({error:"Unable to load payments"},500);return out({payments:data||[]});}
case "notifications":{const {data,error}=await db.from("notifications").select("*").eq("recipient_type","admin").eq("recipient_id","admin").order("created_at",{ascending:false}).limit(Number(b.limit)||100);if(error)return out({error:"Unable to load notifications"},500);return out({notifications:data||[]});}
case "notification_read":{const {data,error}=await db.from("notifications").update({is_read:true,read_at:new Date().toISOString(),status:"read"}).eq("id",b.notification_id).eq("recipient_type","admin").eq("recipient_id","admin").select("*").single();if(error)return out({error:"Unable to update notification"},400);return out({notification:data});}
case "notifications_read_all":{const {error}=await db.from("notifications").update({is_read:true,read_at:new Date().toISOString(),status:"read"}).eq("recipient_type","admin").eq("recipient_id","admin").eq("is_read",false);if(error)return out({error:"Unable to update notifications"},400);return out({success:true});}
case "notification_delete":{const {error}=await db.from("notifications").delete().eq("id",b.notification_id).eq("recipient_type","admin").eq("recipient_id","admin");if(error)return out({error:"Unable to delete notification"},400);return out({success:true});}
case "service_prices":{const {data,error}=await db.from("service_prices").select("*").order("service_name");if(error)return out({error:"Unable to load service prices"},500);return out({prices:data||[]});}
case "save_service_prices":{const updates=Array.isArray(b.updates)?b.updates:[];if(updates.length>200)return out({error:"Too many price updates"},400);for(const u of updates){if(!u?.id||Number(u.base_price)<0||Number(u.gst_rate)<0||Number(u.platform_fee)<0||Number(u.commission_rate)<0)return out({error:"Invalid service price"},400);const {error}=await db.from("service_prices").update({base_price:Number(u.base_price)||0,gst_rate:Number(u.gst_rate)||0,platform_fee:Number(u.platform_fee)||0,commission_rate:Number(u.commission_rate)||0,is_active:Boolean(u.is_active),updated_at:new Date().toISOString()}).eq("id",String(u.id));if(error)return out({error:"Unable to save service prices"},400);}return out({success:true});}
case "site_settings":{const {data,error}=await db.from("site_settings").select("*").eq("id",1).maybeSingle();if(error)return out({error:"Unable to load site settings"},500);return out({settings:data||null});}
case "save_site_settings":{const input=b.input||{};const urlFields=["google_business_url","facebook_url","instagram_url","twitter_url","youtube_url","website_url"];for(const key of urlFields){const value=String(input[key]||"").trim();if(value){try{const u=new URL(value);if(!["http:","https:"].includes(u.protocol))return out({error:"Invalid site URL"},400);}catch{return out({error:"Invalid site URL"},400);}}}const wa=String(input.whatsapp_number||"").replace(/\D/g,"");if(wa&& (wa.length<10||wa.length>15))return out({error:"Invalid WhatsApp number"},400);const payload={id:1,google_business_url:String(input.google_business_url||"").trim()||null,facebook_url:String(input.facebook_url||"").trim()||null,instagram_url:String(input.instagram_url||"").trim()||null,twitter_url:String(input.twitter_url||"").trim()||null,youtube_url:String(input.youtube_url||"").trim()||null,whatsapp_number:String(input.whatsapp_number||"").trim()||null,website_url:String(input.website_url||"").trim()||null,updated_at:new Date().toISOString(),updated_by:String(b.admin_id)};const {error}=await db.from("site_settings").upsert(payload,{onConflict:"id"});if(error)return out({error:"Unable to save site settings"},400);return out({success:true});}
default:return out({error:"Invalid action"},400)}}catch{return out({error:"Unexpected server error"},500)}});