import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization,X-Client-Info,Apikey"};
const supabase=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
async function auth(token:string){const {data}=await supabase.from("technician_auth_sessions").select("technician_id,expires_at").eq("token",token).maybeSingle();if(!data||new Date(data.expires_at)<=new Date())return null;return data.technician_id;}
function out(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});try{const body=await req.json();const technicianId=await auth(body.session_token||"");if(!technicianId)return out({error:"Unauthorized"},401);
switch(body.action){
case "account":{const [{data:technician},{data:jobs},{data:transactions},{data:recharges},{data:notifications},{data:jobNotifications}]=await Promise.all([
supabase.from("technicians").select("id,full_name,mobile,email,city,service_categories,experience_years,status,whatsapp_number,area,pincode,available_days,working_time,has_vehicle,has_tools,profile_photo_url,rating,total_jobs,completed_jobs,is_online,last_active_at,wallet_balance,wallet_locked,created_at,updated_at").eq("id",technicianId).single(),
supabase.from("technician_jobs").select("id,booking_id,technician_id,status,assigned_at,accepted_at,started_at,completed_at,service_type,customer_name,customer_mobile,customer_address,scheduled_date,scheduled_time,notes,amount,call_rate_fee").eq("technician_id",technicianId).order("assigned_at",{ascending:false}),
supabase.from("wallet_transactions").select("*").eq("technician_id",technicianId).order("created_at",{ascending:false}).limit(20),
supabase.from("wallet_recharges").select("*").eq("technician_id",technicianId).order("created_at",{ascending:false}).limit(10),
supabase.from("technician_notifications").select("*").eq("technician_id",technicianId).order("created_at",{ascending:false}).limit(30),
supabase.from("notifications").select("*").eq("recipient_type","technician").eq("recipient_id",technicianId).order("created_at",{ascending:false}).limit(30)]);return out({technician,jobs:jobs||[],transactions:transactions||[],recharges:recharges||[],notifications:notifications||[],jobNotifications:jobNotifications||[]});}
case "online":{const {data,error}=await supabase.from("technicians").update({is_online:!!body.online,last_active_at:new Date().toISOString()}).eq("id",technicianId).select("id,is_online,last_active_at").single();if(error)return out({error:"Unable to update online status"},400);return out({technician:data});}
case "job_status":{if(!body.job_id||!body.status)return out({error:"Job and status are required"},400);const transitions:Record<string,string[]>={
assigned:["accepted","rejected"],accepted:["on_the_way","rejected"],on_the_way:["in_progress"],in_progress:["job_started","completed"],job_started:["job_completed","completed"],job_completed:["completed"],completed:[],rejected:[]
};const requested=String(body.status);const {data:current,error:ce}=await supabase.from("technician_jobs").select("id,status,booking_id").eq("id",body.job_id).eq("technician_id",technicianId).maybeSingle();if(ce||!current)return out({error:"Job not found"},404);const allowed=transitions[String(current.status)]||[];if(!allowed.includes(requested))return out({error:"Invalid job status transition"},409);const update:any={status:requested};if(requested==="completed"||requested==="job_completed")update.completed_at=new Date().toISOString();const {data,error}=await supabase.from("technician_jobs").update(update).eq("id",body.job_id).eq("technician_id",technicianId).eq("status",current.status).select("id,booking_id,technician_id,status,assigned_at,completed_at").maybeSingle();if(error)return out({error:"Unable to update job status"},400);if(!data)return out({error:"Job status changed concurrently. Please retry."},409);
const bookingStatus:Record<string,string>={accepted:"accepted",on_the_way:"on_the_way",in_progress:"in_progress",job_started:"job_started",job_completed:"job_completed",completed:"completed"};
if(requested==="rejected"){
  await supabase.from("bookings").update({assigned_technician_id:null,status:"pending",updated_at:new Date().toISOString()}).eq("id",current.booking_id).eq("assigned_technician_id",technicianId).in("status",["assigned","accepted"]);
}else if(bookingStatus[requested]){
  await supabase.from("bookings").update({status:bookingStatus[requested],updated_at:new Date().toISOString()}).eq("id",current.booking_id).eq("assigned_technician_id",technicianId);
}
return out({job:data});}
case "notification_read":{if(!body.notification_id)return out({error:"Notification ID is required"},400);const source=String(body.source||"wallet");const table=source==="job"?"notifications":"technician_notifications";let q=supabase.from(table).update({is_read:true,read_at:new Date().toISOString(),status:"read"}).eq("id",body.notification_id);q=source==="job"?q.eq("recipient_type","technician").eq("recipient_id",technicianId):q.eq("technician_id",technicianId);const {error}=await q;if(error)return out({error:"Unable to update notification"},400);return out({success:true});}
case "notifications_read_all":{const a=await supabase.from("technician_notifications").update({is_read:true}).eq("technician_id",technicianId);const b=await supabase.from("notifications").update({is_read:true,read_at:new Date().toISOString(),status:"read"}).eq("recipient_type","technician").eq("recipient_id",technicianId);if(a.error||b.error)return out({error:"Unable to update notifications"},400);return out({success:true});}
case "recharge":{const amount=Number(body.amount);if(!Number.isFinite(amount)||amount<=0||amount>100000)return out({error:"Invalid amount"},400);const {data,error}=await supabase.from("wallet_recharges").insert({technician_id:technicianId,amount,status:"pending",payment_ref:String(body.payment_ref||"").trim()||null}).select("*").single();if(error)return out({error:"Unable to submit recharge"},400);return out({recharge:data});}
default:return out({error:"Invalid action"},400)}}catch{return out({error:"Unexpected server error"},500)}});