-- Customer-facing prices for each supported appliance job type.
-- Customer prices are separate from technician-paid call-rate fees.
CREATE TABLE IF NOT EXISTS public.customer_service_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_category text NOT NULL,
  service_type text NOT NULL,
  base_price numeric(10,2) NOT NULL CHECK (base_price >= 0),
  price_label text NOT NULL DEFAULT 'Starting service price',
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT customer_service_prices_category_type_key UNIQUE (service_category, service_type)
);

ALTER TABLE public.customer_service_prices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS customer_service_prices_public_read ON public.customer_service_prices;
CREATE POLICY customer_service_prices_public_read
  ON public.customer_service_prices
  FOR SELECT TO anon, authenticated
  USING (is_active = true);

-- Initial customer price schedule. GST (18%) and the existing ₹30 customer
-- platform fee are shown separately at checkout. Materials/spares require approval.
INSERT INTO public.customer_service_prices
  (service_category, service_type, base_price, price_label, is_active)
VALUES
  ('AC Service', 'General Service', 499, 'AC general service', true),
  ('AC Service', 'Installation', 1499, 'AC installation', true),
  ('AC Service', 'Gas Filling', 1999, 'AC gas filling', true),
  ('AC Service', 'Pump Water Service', 499, 'AC pump water service', true),
  ('AC Service', 'Coil Service', 1499, 'AC coil service', true),
  ('AC Repair', 'General Service', 499, 'AC general service', true),
  ('AC Repair', 'Installation', 1499, 'AC installation', true),
  ('AC Repair', 'Gas Filling', 1999, 'AC gas filling', true),
  ('AC Repair', 'Pump Water Service', 499, 'AC pump water service', true),
  ('AC Repair', 'Coil Service', 1499, 'AC coil service', true),
  ('Washing Machine', 'Washing Machine Service', 399, 'Washing machine service', true),
  ('Washing Machine Repair', 'Washing Machine Service', 399, 'Washing machine service', true),
  ('Refrigerator', 'Refrigerator Service', 399, 'Refrigerator service', true),
  ('Refrigerator Repair', 'Refrigerator Service', 399, 'Refrigerator service', true)
ON CONFLICT (service_category, service_type)
DO UPDATE SET
  base_price = EXCLUDED.base_price,
  price_label = EXCLUDED.price_label,
  is_active = EXCLUDED.is_active,
  updated_at = now();
