-- Technician-paid call rates vary by the exact appliance job, not only broad category.
-- Customer-facing service prices/platform fees remain separate.
ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS service_type text;

ALTER TABLE public.technician_jobs
  ADD COLUMN IF NOT EXISTS service_type text;

CREATE TABLE IF NOT EXISTS public.technician_call_rates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_category text NOT NULL,
  service_type text NOT NULL,
  call_rate_fee numeric(10,2) NOT NULL CHECK (call_rate_fee >= 0),
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT technician_call_rates_category_type_key UNIQUE (service_category, service_type)
);

ALTER TABLE public.technician_call_rates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS technician_call_rates_public_read ON public.technician_call_rates;
CREATE POLICY technician_call_rates_public_read
  ON public.technician_call_rates FOR SELECT TO anon, authenticated USING (is_active = true);

INSERT INTO public.technician_call_rates (service_category, service_type, call_rate_fee, is_active)
VALUES
  ('AC Service', 'General Service', 150, true),
  ('AC Service', 'Installation', 500, true),
  ('AC Service', 'Gas Filling', 500, true),
  ('AC Service', 'Pump Water Service', 500, true),
  ('AC Service', 'Coil Service', 800, true),
  ('AC Repair', 'General Service', 150, true),
  ('AC Repair', 'Installation', 500, true),
  ('AC Repair', 'Gas Filling', 500, true),
  ('AC Repair', 'Pump Water Service', 500, true),
  ('AC Repair', 'Coil Service', 800, true),
  ('Washing Machine', 'Washing Machine Service', 200, true),
  ('Washing Machine Repair', 'Washing Machine Service', 200, true),
  ('Refrigerator', 'Refrigerator Service', 200, true),
  ('Refrigerator Repair', 'Refrigerator Service', 200, true)
ON CONFLICT (service_category, service_type)
DO UPDATE SET
  call_rate_fee = EXCLUDED.call_rate_fee,
  is_active = EXCLUDED.is_active,
  updated_at = now();

-- Keep the broad category-level fee sensible for older admin views.
-- New bookings use technician_call_rates and snapshot the exact job-specific fee.
UPDATE public.service_prices
SET call_rate_fee = CASE
  WHEN service_name IN ('AC Repair', 'AC Service') THEN 150
  WHEN service_name IN ('Washing Machine', 'Washing Machine Repair',
                        'Refrigerator', 'Refrigerator Repair') THEN 200
  ELSE call_rate_fee
END,
updated_at = now()
WHERE service_name IN (
  'AC Repair', 'AC Service',
  'Washing Machine', 'Washing Machine Repair',
  'Refrigerator', 'Refrigerator Repair'
);
